version: '1.0.0'
services:

#      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
#    expose:
#      - "9092"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: transactions:4:1, DLQ:1:1, wallet:1:1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always


  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb

#  app:
#    container_name: app-springboot-demo
#    image: app-springboot-demo
#    build: ./
#    ports:
#      - "8081:8081"
##      - "5005:5005"
#    depends_on:
#      - dbpostgresql
#      - kafka
#    environment:
#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005
#    restart: always


  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    restart: always
    container_name: zookeeper


